/* SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause) */

#ifndef __DT_BINDINGS_CLOCK_NEXELL_S5P6818_H
#define __DT_BINDINGS_CLOCK_NEXELL_S5P6818_H

#define NEXELL_CLK_XIN		0
#define NEXELL_CLK_PLL0		1
#define NEXELL_CLK_PLL1		2
#define NEXELL_CLK_PLL2		3
#define NEXELL_CLK_PLL3		4

#define NEXELL_CLK_UART0	5
#define NEXELL_CLK_TIMER0	6
#define NEXELL_CLK_TIMER1	7
#define NEXELL_CLK_SDMMC0	8
#define NEXELL_CLK_SDMMC1	9
#define NEXELL_CLK_SDMMC2	10
#define NEXELL_CLK_GMAC		11
#define NEXELL_CLK_GMAC_TX	12
#define NEXELL_CLK_USBHOST	13
#define NEXELL_CLK_USBHOST_REF	14
#define NEXELL_CLK_MIPI		15
#define NEXELL_CLK_I2C0		16
#define NEXELL_CLK_I2C1		17
#define NEXELL_CLK_I2C2		18

#define NEXELL_CLK_MAX		19

#endif
